### ISSUE TITLE
TypeError: main() got an unexpected keyword argument 'whois'

### ISSUE THREAD

**Issue by codejimr** [0xbharath/domains-from-csp#2]
python csp_parser.py  -u https://hackerone.com -r
Traceback (most recent call last):
  File "csp_parser.py", line 129, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: main() got an unexpected keyword argument 'whois'

**Comment by s0i37** [comment]
I had same error. Just change:
```
-@click.option('--check-whois/--no-check-whois', '--whois', default=False,
+@click.option('--check-whois/--no-check-whois', '-w', default=False,
```
